language: node_js
node_js:
  - '0.10'
services:
  - redis-server
after_success:
  - npm run coveralls
env:
  global:
    - COVERALLS_SERVICE_NAME="travis-ci"
    - secure: "V4XydjkUdqkChbTeMVxkWTIVLeEdIGbUkVl24QgTHJrtC+hU0XlE8T26pP/BG4jzEJS58rXfFGDt8Y50g5h5CbG2hbjbeM0+y8hWWiOZWXIxiyYRiHS6niEPhsyddAA6MqmVuZFKuFjrDLWwuGSkM3JYp1JjQbXi6UlPo5ReXj8="
sudo: false
notifications:
  email: false
